// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewRestaurant struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	PhoneNumber string `json:"phoneNumber"`
}

type UpdateRestaurant struct {
	Name        *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
	PhoneNumber *string `json:"phoneNumber,omitempty"`
}

type User struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}
