// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package food

import ()

type Restaurant struct {
	ID          int32
	Name        string
	Description string
	PhoneNumber string
}
